# Generated by Django 5.1.7 on 2025-04-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
